kind: pipeline
type: docker
name: blogPublish

clone:
  depth: 1

steps:
  - name: pull
    image: bitnami/git
    volumes:
      - name: app
        path: /app
      - name: ssh
        path: /app/ssh
    commands:
      - ls -l /app
      - ls -l /app/ssh
      - ssh-add /app/ssh/id_rsa
      - cd /app/BlogGenerate
      - ls -l
      - git pull
      - cd /app/blogPublish/source/_posts/technology-note
      - git pull
      - ls
#  - name: package
#    image: node:16-bullseye
#    volumes:
#      - name: app
#        path: /app
#    commands:
#      - cd /app
#      - npm install -g hexo --registry=https://registry.npmmirror.com
#      - npm install --registry=https://registry.npmmirror.com
#      - hexo v && hexo clean && hexo g
#      - cd  public
#      - tar -czf  ../dist.tar.gz  *
#      - cd  public
#  - name: deploy
#    image: drillster/drone-rsync
#    settings:
#      hosts: [ "fleyx.com:22000" ]
#      source: ./target
#      target: ~/packages
#      include: [ "app.jar", "app.jar.md5" ]
#      script:
#        - cd ~/packages
#        - md5sum -c app.jar.md5
volumes: # 定义流水线挂载目录，用于共享数据
  - name: app
    host:
      path: /dataPool/systemData/linux_env/data/drone/workspace/blogPublish
  - name: ssh
    host:
      path: /dataPool/systemData/linux_env/data/drone/ssh
