kind: pipeline
type: docker
name: blogPublish

clone:
  depth: 1

steps:
  - name: pull
    image: bitnami/git
    environment:
      privateKey:
        from_secret: privateSsh
    commands:
      - echo $privateKey
      - echo $privateKey > sshKey
      - eval $(ssh-agent)
      - cat sshKey
      - ssh-add sshKey
      - sleep 100
      - cd /app/BlogGenerate
      - ls -l
      - git pull
      - cd /app/blogPublish/source/_posts/technology-note
      - git pull
      - ls
#  - name: package
#    image: node:16-bullseye
#    volumes:
#      - name: app
#        path: /app
#    commands:
#      - cd /app
#      - npm install -g hexo --registry=https://registry.npmmirror.com
#      - npm install --registry=https://registry.npmmirror.com
#      - hexo v && hexo clean && hexo g
#      - cd  public
#      - tar -czf  ../dist.tar.gz  *
#      - cd  public
#  - name: deploy
#    image: drillster/drone-rsync
#    settings:
#      hosts: [ "fleyx.com:22000" ]
#      source: ./target
#      target: ~/packages
#      include: [ "app.jar", "app.jar.md5" ]
#      script:
#        - cd ~/packages
#        - md5sum -c app.jar.md5